name: Create Kaoto-next tag and release
on:
  workflow_dispatch:
    inputs:
      tag_version:
        type: The tag to release
        description: The tag version we want to release
        required: true
      commit_sha:
        type: Point the tag/release to a specific commit sha
        description: The commit sha to tag
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.tag_version.inputs.tag_version }}
          default_bump: false
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
