name: Create Kaoto-next tag and release
on:
  workflow_dispatch:
    inputs:
      tag_version:
        type: The tag to release
        description: The tag version we want to release
        required: true
      commit:
        type: Point the tag/release to a specific commit sha
        description: The commit sha to tag
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - uses: avakar/tag-and-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_version }}
        commit: ${{ github.event.inputs.commit }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
