name: Release Kaoto next on tag push

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        body: "New release for tag"
